### ISSUE TITLE
MPD password?

### ISSUE THREAD

**Issue by ReekyMarko** [kori/wylt#3]
Couldn't find any documentation on telling libra about my MPD password. Is this not implemented yet or just not documented?

**Comment by kori** [comment]
It's not implemented yet, my bad.

**Comment by ReekyMarko** [comment]
Oh okay. Should not be too hard to implement, so I might have a look at this when I get the time (during this fall) if nobody does that before me. I haven't written any go before so might take a while

**Comment by kori** [comment]
I'd really appreciate it. If you could also look at issue #2, I can review that.

**Comment by kori** [comment]
Solved with 33ca606f
